#-------------通用配置---------------#
server:
  ssl:
    key-store: classpath:key/rsakey.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcatjks
    urls: /*
  port: 8443
  non-ssl-port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
jwt:
  header: Authorization
  tokenParam: accessToken
  secret: 9a5bc29c50ad11e7b114b2f933d5fe66
  expiration: 7200
  tokenHead: "Bearer "

---
#------------开发环境配置-------------#
spring:
  profile: dev
  datasource:
    url: jdbc:oracle:thin:@172.18.30.32:1521:deve
    username: devefdtdt
    password: devefdtdt
  redis:
    host: 101.200.34.191
    port: 6379
    password: datacrawler

---
#------------测试环境配置-------------#
spring:
  profile: test
  datasource:
    url: jdbc:oracle:thin:@172.18.30.32:1521:deve
    username: devefdtdt
    password: devefdtdt

---
#------------生产环境配置-------------#
spring:
  profile: prod
  datasource:
    url: jdbc:oracle:thin:@172.18.30.32:1521:deve
    username: devefdtdt
    password: devefdtdt